repos:
  - repo: local
    hooks:
      - id: code-analysis
        name: Code analysis
        entry: bin/code-analysis
        language: script
        files: src/(.*)
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies:
          - isort[pyproject]
