name: starzel buildout

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.7, 3.8, 3.9]

    steps:
      # git checkout
      - uses: actions/checkout@v2

      # python setup
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      # python cache
      - uses: actions/cache@v1
        with:
          path: |
            ~/.cache/pip
            ~/buildout-cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # before install 1
      - name: Prepare mrbob answers
        run: |
          echo "[variables]" > $HOME/mrbob_answers.txt
          echo "package.type = Basic" >> $HOME/mrbob_answers.txt
          echo "package.namespace = project" >> $HOME/mrbob_answers.txt
          echo "package.namespace2 =" >> $HOME/mrbob_answers.txt
          echo "package.name = site" >> $HOME/mrbob_answers.txt
          echo "package.description = A Dummy package" >> $HOME/mrbob_answers.txt
          echo "package.git.disabled = True" >> $HOME/mrbob_answers.txt
          echo "author.name = Philip Bauer" >> $HOME/mrbob_answers.txt
          echo "author.email = bauer@starzel.de" >> $HOME/mrbob_answers.txt
          echo "author.github.user = pbauer" >> $HOME/mrbob_answers.txt
          echo "plone.version = 5.2" >> $HOME/mrbob_answers.txt
          echo "python.version = 3.7" >> $HOME/mrbob_answers.txt
          echo "vscode_support = False" >> $HOME/mrbob_answers.txt

      - name: before install
        run: |
          mkdir -p $HOME/buildout-cache/{downloads,eggs,extends}
          mkdir -p $HOME/buildout-cache/{downloads,eggs,extends}
          mkdir -p $HOME/.buildout
          echo "[buildout]" > $HOME/.buildout/default.cfg
          echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
          echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
          echo "extends-cache = $HOME/buildout-cache/extends" >> $HOME/.buildout/default.cfg
          echo "abi-tag-eggs = true" >> $HOME/.buildout/default.cfg
          git config --global user.email "githubaction@github.com"
          git config --global user.name "GitHub Action CI"

      # - name: Virtualenv install
      #   run: |
      #     echo `which python`
      #     pip install virtualenv
      #     virtualenv -p `which python` .

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mr.bob
          pip install bobtemplates.plone

      - name: Run buildout
        run: |
          echo -e "[buildout]\nlogin = admin\npassword = admin" > secret.cfg
          ln -s local_develop.cfg local.cfg
          buildout -N code-analysis:return-status-codes=True annotate
          buildout -N code-analysis:return-status-codes=True

      - name: Create addon and re-run buildout
        run: |
          mkdir src
          pip install tox
          mrbob -O src/project.site --config $HOME/mrbob_answers.txt bobtemplates.plone:addon
          # add that package to buildout.cfg in eggs, testeggs, auto-checkout and [sources]
          sed -i "15i \    project.site" buildout.cfg
          sed -i "19i \    project.site [test]" buildout.cfg
          sed -i "23i \    project.site" buildout.cfg
          sed -i "29i project.site = fs project.site full-path=\${buildout\:directory}/src/project.site" buildout.cfg
          # re-run buildout
          buildout -N code-analysis:return-status-codes=True

      - name: test
        run: bin/coverage-test
